// Data catalog — mirror del diagrams/02-deployment-copilot-v2.drawio
export const PALETTE = {
  env:            { fill: 'transparent', stroke: '#444',    text: '#1F2933', dashed: true },
  'node-active':  { fill: '#FFFFFF',     stroke: '#6B6B6B', text: '#1F2933' },
  'node-passive': { fill: '#E8E8E8',     stroke: '#999',    text: '#333' },
  unit:           { fill: '#438DD5',     stroke: '#2E6295', text: '#FFFFFF' },
  'unit-new':     { fill: '#2E7D32',     stroke: '#1B5E20', text: '#FFFFFF' },
  'unit-modified':{ fill: '#E65100',     stroke: '#BF360C', text: '#FFFFFF' },
  system:         { fill: '#8C8496',     stroke: '#6F6878', text: '#FFFFFF' },
  'system-future':{ fill: '#B59CC9',     stroke: '#8E6FA6', text: '#FFFFFF' },
  core:           { fill: '#5E4E6E',     stroke: '#3A2F47', text: '#FFFFFF' },
};

export const nodes = [
  { id: 'env-onprem',  type: 'env', name: 'Tuya — Endpoints corporativos', kind: 'Environment: on premise', desc: 'Estaciones de los desarrolladores.' },
  { id: 'env-github',  type: 'env', name: 'GitHub Cloud — Enterprise tuyacol', kind: 'Environment: cloud', desc: 'SaaS de GitHub.' },
  { id: 'env-azure',   type: 'env', name: 'Azure — Plataforma MCPs dev', kind: 'Environment: cloud', desc: 'Suscripcion de desarrollo.' },

  { id: 'node-ws',          parent: 'env-onprem', type: 'node-active', name: 'Equipo del desarrollador', kind: 'Workstation', desc: 'IDE, CLI, MCPs locales.' },
  { id: 'node-github-saas', parent: 'env-github', type: 'node-active', name: 'GitHub.com / Copilot SaaS', kind: 'SaaS · 99.9%', desc: 'Proxy, modelos, audit, metrics.' },
  { id: 'node-apim',        parent: 'env-azure',  type: 'node-active', name: 'Azure API Management', kind: 'API Gateway', desc: 'Enruta hacia el MCP.' },
  { id: 'node-acr',         parent: 'env-azure',  type: 'node-active', name: 'Azure Container Registry', kind: 'Container Registry', desc: 'Mirror corporativo.' },
  { id: 'node-aks',         parent: 'env-azure',  type: 'node-active', name: 'AKS desarrollo', kind: 'K8s Cluster', desc: 'Aloja namespace MCP.' },
  { id: 'ns-mcp',           parent: 'node-aks',   type: 'node-active', name: 'Namespace MCP dev', kind: 'K8s Namespace', desc: 'Aisla workloads.' },

  { id: 'u-vscode',    parent: 'node-ws', type: 'unit', name: 'VS Code + Copilot', kind: 'IDE Extension', desc: 'Chat, agente, plan.' },
  { id: 'u-cli',       parent: 'node-ws', type: 'unit', name: 'Copilot CLI', kind: 'CLI', desc: 'Cliente en terminal.' },
  { id: 'u-mcps-local',parent: 'node-ws', type: 'unit', name: 'MCPs locales', kind: 'Local MCP', desc: 'stdio/JSON-RPC.' },
  { id: 'u-shell',     parent: 'node-ws', type: 'unit', name: 'Shell', kind: 'Shell', desc: 'Comandos del agente.' },
  { id: 'u-git',       parent: 'node-ws', type: 'unit', name: 'Cliente Git', kind: 'Git', desc: 'Push/pull a AzDO.' },
  { id: 'u-workspace', parent: 'node-ws', type: 'unit', name: 'Workspace local', kind: 'File System', desc: 'Codigo abierto.', gap: 'D1' },
  { id: 'u-browser',   parent: 'node-ws', type: 'unit', name: 'Navegador', kind: 'Browser', desc: 'Consola admin.' },

  { id: 'u-proxy',       parent: 'node-github-saas', type: 'unit', name: 'Proxy Copilot', kind: 'API', desc: 'Enruta prompts.' },
  { id: 'u-llm',         parent: 'node-github-saas', type: 'unit', name: 'Servicio LLM', kind: 'LLM', desc: 'Inferencia.' },
  { id: 'u-console',     parent: 'node-github-saas', type: 'unit', name: 'Consola admin', kind: 'Web App', desc: 'Licencias.', gap: 'D1' },
  { id: 'u-audit-api',   parent: 'node-github-saas', type: 'unit', name: 'Audit Log API', kind: 'API', desc: 'Eventos.', gap: 'D3' },
  { id: 'u-metrics-api', parent: 'node-github-saas', type: 'unit', name: 'Metrics API', kind: 'API', desc: 'Adopcion.', gap: 'D4' },
  { id: 'u-license',     parent: 'node-github-saas', type: 'unit', name: 'Licenciamiento', kind: 'API', desc: 'Entitlement.' },
  { id: 'u-azdo-repos',  parent: 'node-github-saas', type: 'unit', name: 'Azure DevOps Repos', kind: 'Git Hosting', desc: 'Repos.' },
  { id: 'u-audit-store', parent: 'node-github-saas', type: 'unit', name: 'Audit Storage', kind: 'Log Store', desc: 'Retencion.' },

  { id: 'u-api-sonar',   parent: 'node-apim', type: 'unit', name: 'API SonarCloud MCP', kind: 'APIM Route', desc: 'Enruta al cluster.' },
  { id: 'u-image-sonar', parent: 'node-acr',  type: 'unit', name: 'Imagen MCP', kind: 'OCI Image', desc: 'Mirror.' },
  { id: 'u-acr-replica', parent: 'node-acr',  type: 'node-passive', name: 'Replica geo ACR', kind: 'Reg pasivo', desc: 'Failover.' },

  { id: 'u-ingress',    parent: 'ns-mcp', type: 'unit', name: 'Ingress', kind: 'K8s Service', desc: 'Publica el pod.' },
  { id: 'u-mcp-server', parent: 'ns-mcp', type: 'unit', name: 'SonarCloud MCP Server', kind: 'MCP Server', desc: 'Pod JSON-RPC.' },
  { id: 'u-token',      parent: 'ns-mcp', type: 'unit-modified', name: 'Token admin **', kind: 'Env Var', desc: 'Secreto.', gap: 'F2' },
  { id: 'u-csi',        parent: 'ns-mcp', type: 'unit-new', name: 'CSI Secrets Driver ++', kind: 'K8s CSI', desc: 'Recomendado.' },
  { id: 'u-logs',       parent: 'ns-mcp', type: 'unit', name: 'Logs MCP', kind: 'Container Logs', desc: 'stdout/stderr.' },
  { id: 'u-template',   parent: 'ns-mcp', type: 'unit-new', name: 'Template MCPs ++', kind: 'Helm', desc: 'Base reutilizable.', gap: 'F3' },

  { id: 'sys-netskope', type: 'system', name: 'Netskope SWG', kind: 'Software System', desc: 'Gateway corporativo.', gap: 'E1' },
  { id: 'sys-entra',    type: 'core',   name: 'Microsoft Entra ID', kind: 'Core System', desc: 'IdP.', gap: 'A4' },
  { id: 'sys-sonar',    type: 'system', name: 'SonarCloud', kind: 'Software System', desc: 'Consultado por MCP.' },
  { id: 'sys-kv',       type: 'system-future', name: 'Azure Key Vault ++', kind: 'Software System', desc: 'Boveda recomendada.', gap: 'F2' },
  { id: 'sys-siem',     type: 'system-future', name: 'SIEM corporativo', kind: 'SW · futuro', desc: 'Audit destino.', gap: 'D3' },
  { id: 'sys-bi',       type: 'system-future', name: 'BI / Adopcion', kind: 'SW · futuro', desc: 'Metrics consumer.', gap: 'D4' },
];

export const edges = [
  ['u-vscode','u-workspace','Lee contexto','FS local'],
  ['u-cli','u-workspace','Lee contexto','FS local'],
  ['u-vscode','u-mcps-local','Invoca','JSON-RPC'],
  ['u-cli','u-mcps-local','Invoca','JSON-RPC'],
  ['u-vscode','u-shell','Ejecuta','Proceso'],
  ['u-cli','u-shell','Ejecuta','Proceso'],
  ['u-git','u-azdo-repos','Push/pull','Git/HTTPS'],
  ['u-vscode','sys-netskope','Envia prompts','JSON/HTTPS'],
  ['u-cli','sys-netskope','Envia prompts','JSON/HTTPS'],
  ['u-browser','u-console','Administra','HTML/HTTPS'],
  ['sys-netskope','u-proxy','Egress Copilot','JSON/HTTPS'],
  ['u-proxy','u-llm','Inferencia','API/HTTPS'],
  ['u-proxy','u-license','Entitlement','JSON/HTTPS'],
  ['u-license','sys-entra','SSO','SAML/OIDC'],
  ['u-console','sys-entra','Auth admin','SAML/SCIM'],
  ['u-audit-api','u-audit-store','Persiste','interno'],
  ['u-audit-api','sys-siem','Debe exportar','JSON/HTTPS', true],
  ['u-metrics-api','sys-bi','Debe consumir','JSON/HTTPS', true],
  ['sys-netskope','u-api-sonar','Egress MCP','JSON/HTTPS'],
  ['u-api-sonar','u-ingress','Enruta','HTTPS'],
  ['u-ingress','u-mcp-server','Forward','HTTP'],
  ['u-mcp-server','u-token','Lee token','Env Var'],
  ['u-mcp-server','sys-sonar','Consulta','JSON/HTTPS'],
  ['u-mcp-server','u-logs','Logs','stdout'],
  ['node-aks','u-image-sonar','Descarga imagen','OCI'],
  ['u-image-sonar','u-acr-replica','Replica','OCI', true],
  ['u-mcp-server','u-csi','Debe consumir','FS volume', true],
  ['u-csi','sys-kv','Monta secretos','JSON/HTTPS', true],
];
